### ISSUE TITLE
Interrupts

### ISSUE THREAD

**Issue by narimaulea** [MarkMegarry/AVR8js-Falstad#8]
Hi Mark. Do you think it would be difficult to implement interruptions?
For example , RISING, FALLING OR LOW.
Thanks

**Comment by mark-mega** [comment]
Hi there, 

I'll have to preface this by saying that I haven't touched this project since 2020, and the most recent official repo seems to be [here](https://github.com/pfalstad/circuitjs1). Also, if you need a circuit simulator that features Arduino simulation, I would highly recommend that you check out [Tinkercad](https://www.tinkercad.com/) if you haven't already, its circuit editor boasts an Arduino simulator good enough for teaching. [Wokwi](https://wokwi.com/projects/new/arduino-uno) also seem to have a nice Arduino circuit simulator, but I haven't used it recently and it seems to be more Arduino-first than Falstad.

Now in terms of implementing interrupts, the Arduino side of the code in this repo simply sends the user's source code to Wokwi's compiler api at https://hexi.wokwi.com (using buildHex in /AVR8js/demo/src/compile.ts) and runs the result (using executeProgram in /AVR8js/demo/src/index.ts). Assuming this compiler supports interrupts (I would be very surprised if it didn't), then the problem might be related to how the state of the pin (as determined by the Falstad simulator) is presented to Wokwi's Arduino simulator. You'll notice that the [Falstad Arduino examples](https://www.falstad.com/circuit/avr8js/index.html) utilise two different components for Arduino inputs and Arduino outputs, I'd suggest that a good starting point to implement interrupts would be to investigate how the "external voltage (Javascript)" and "labelled node" components use Arduino data. This will probably require becoming familiar with Falstad's Javascript interface.

Wish I could be more helpful right now, but let me know if you've any other questions I can answer.

**Comment by mark-mega** [comment]
After having a closer look at the [more up-to-date repo](https://github.com/pfalstad/circuitjs1) mentioned earlier, it looks like a file to start looking at is /war/avr8js/src.avr8js.js. This file appears to control all of the Arduino simulation, and simply gets or sets voltages in the circuit simulation based on the Arduino simulation. Two functions of interest are defined in this file:

```
execute(callback) {
    var runner = this;

    this.sim.ontimestep = function () {
      var timeDiff = runner.sim.getTime() - runner.prevTime; //Added by Mark Megarry

      var cyclesToRun = runner.cpu.cycles + timeDiff * runner.speed; //Added by Mark Megarry

      runner.getPinStates();

      while (runner.cpu.cycles < cyclesToRun) {
        avr8js_1.avrInstruction(runner.cpu);
        runner.cpu.tick();
      }

      runner.prevTime = runner.sim.getTime();
      callback(runner.cpu);
    };
  }
```

and

```
getPinStates() {
    var i;

    for (i = 0; i != 14; i++) {
      var port = this.portD;
      var pn = i;

      if (i >= 8) {
        port = this.portB;
        pn = i - 8;
      }

      var ps = port.pinState(pn);
      if (ps == avr8js_1.PinState.Input) port.setPin(pn, this.sim.getNodeVoltage("pin " + i) > 2.5);else this.sim.setExtVoltage("pin " + i, ps == avr8js_1.PinState.High ? 5 : 0);
    }
  }
```

We can see that the execute(callback) function calculates the numberof CPU cycles to run (based on the simulation time difference between the last execution and the current execution) and calls the `getPinStates()` function, which gets or sets the voltage at each Arduino pin in the simulation based on the pin's `pinState` (can be low, high, input, input pullup).

Coming back to your question, I'm still not sure why interrupt inputs don't work in the current version, but I would imagine that the problem lies somewhere within the avr8js.js file. It might be best to open another issue on the [most recent repo](https://github.com/pfalstad/circuitjs1) asking the same question.

**Comment by narimaulea** [comment]
Thanks Mark for your time. Your work is great !
I made a new issue in the [most recent repo](https://github.com/pfalstad/circuitjs1) .

**Comment by mark-mega** [comment]
Thank you, I hope someone gets to the bottom of this problem.
